#ifndef ERROR_CODES_H
#define ERROR_CODES_H

#define ERR_OKAY                0
#define ERR_ARGS_PARSE_FAILED   1
#define ERR_SERVER_MSOC_FAILED  2
#define ERR_SERVER_BIND_FAILED  3
#define ERR_ALLOCATION_FAILED   4
#define ERR_CONN_TERMINATED     5

#endif // ERROR_CODES_H
